parameters:
- name: region
  displayName: AWS Region
  type: string
  default: us-east-1
  values:
  - us-east-1
  - us-west-2
  - eu-central-1
  - eu-west-2
  - ap-southeast-1
  - ap-northeast-1

#trigger:
#- develop
trigger: none


pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run test
    npm run lint
    npm run compile
  displayName: 'npm install and build'

- script: |
    cp package.json lib/
    npm install --prefix lib/ --production
    rm -rf lib/node_modules/aws-sdk
    cd lib
    zip -x\*.zip -qr9 "autotag-local-$(Build.BuildNumber).zip" -- *
    ls . 
  displayName: 'Create ZIP'

- task: S3Upload@1
  displayName: 'Upload ZIP to S3 bucket'
  inputs:
    awsCredentials: 'aws-ems-dev'
    regionName: ${{ parameters.region }}
    bucketName: 's3-jbl-auto-tag'
    createBucket: true
    sourceFolder: './lib'
    targetFolder: 'releases'
    globExpressions: 'autotag-local-$(Build.BuildNumber).zip'

#- task: CloudFormationCreateOrUpdateStack@1
#  inputs:
#    awsCredentials: ${{ parameters.awsCred }}
#    regionName: ${{ parameters.region }}
#    stackName: cft-jbl-auto-tag
#    templateFile: AWS/LandingZone/EMS/cft-jbl-ems-VPCSetup-01.yml
#    templateParametersFile: 'AWS/LandingZone/EMS/parameters-ems-${{ parameters.environment }}-${{ region }}.yml'
#    capabilityIAM: true
#    capabilityNamedIAM: true
