#trigger:
#- develop
trigger: none


pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run test
    npm run lint
    npm run compile
  displayName: 'npm install and build'

- script: |
    cp package.json lib/
    npm install --prefix lib/ --production
    rm -rf lib/node_modules/aws-sdk
    cd lib
    zip -x\*.zip -qr9 "autotag-local.zip" -- *
    ls . 
  displayName: 'Create ZIP'

- task: S3Upload@1
  displayName: 'Upload ZIP to S3 bucket'
  inputs:
    awsCredentials: 'aws-ems-dev'
    regionName: 'us-east-1'
    bucketName: 's3-jbl-auto-tag'
    createBucket: true
    sourceFolder: './lib'
    targetFolder: 'releases'
    globExpressions: 'autotag-local.zip'