parameters:
- name: region
  displayName: AWS Region
  type: string
  default: us-east-1
  values:
  - us-east-1
  - us-west-2
  - eu-central-1
  - eu-west-2
  - ap-southeast-1
  - ap-northeast-1
- name: environment
  displayName: Environment
  type: string
  default: dev
  values:
  - dev
  - stg
  - prd
  - lab

#trigger:
#- develop
trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run test
    npm run lint
    npm run compile
  displayName: 'npm install and build'

- script: |
    cp package.json lib/
    npm install --prefix lib/ --production
    rm -rf lib/node_modules/aws-sdk
    cd lib
    zip -x\*.zip -qr9 "autotag-local-$(Build.BuildNumber).zip" -- *
    ls . 
  displayName: 'Create ZIP'

- task: S3Upload@1
  displayName: 'Upload ZIP to S3 bucket'
  inputs:
    awsCredentials: 'aws-ems-dev'
    regionName: ${{ parameters.region }}
    bucketName: 's3-jbl-auto-tag'
    createBucket: true
    sourceFolder: './lib'
    targetFolder: 'releases'
    globExpressions: 'autotag-local-$(Build.BuildNumber).zip'

- task: CloudFormationCreateOrUpdateStack@1
  displayName: 'CloudFormation deploy main stack in ${{ parameters.region }}'
  inputs:
    awsCredentials: 'aws-ems-dev'
    regionName: ${{ parameters.region }}
    stackName: cf-jbl-auto-tag
    templateFile: ./cloud_formation/event_multi_region_template/autotag_event_main-template.json
    templateParametersSource: 'inline'
    templateParameters: |
      [
        {
          "ParameterKey": "CodeS3Bucket",
          "ParameterValue": "s3-jbl-auto-tag"
        },
        {
          "ParameterKey": "CodeS3Path",
          "ParameterValue": "releases/autotag-local-$(Build.BuildNumber).zip"
        },
        {
          "ParameterKey": "AutoTagDebugLogging",
          "ParameterValue": "Enabled"
        },
        {
          "ParameterKey": "AutoTagTagsCreateTime",
          "ParameterValue": "Enabled"
        },
        {
          "ParameterKey": "AutoTagTagsInvokedBy",
          "ParameterValue": "Enabled"
        },
        {
          "ParameterKey": "LogRetentionInDays",
          "ParameterValue": "90"
        },
        {
          "ParameterKey": "CustomTags",
          "ParameterValue": ""
        }
      ]
    capabilityIAM: true
    capabilityNamedIAM: true
    tags: |
      jbl:name=cft-jbl-${{ parameters.environment }}-${{ parameters.region }}-auto-tag
      jbl:cost_center=4150
      jbl:division=EMS
      jbl:site=GLOBAL
      jbl:project_name=infrastructure
      jbl:owner_email=aws_operations@jabil.com
      jbl:created_date=$(Date:yyyyMMdd)
      jbl:support_team_email=aws_operations@jabil.com

- template: azure-pipelines-collector-template.yml
  parameters:
    region: ${{ parameters.region }}
    regions:
    - us-east-1
    - us-west-2
    - eu-central-1
    - eu-west-2
    - ap-southeast-1
    - ap-northeast-1
    environment: ${{ parameters.environment }}
    awsCred: aws-ems-dev